// Generated by Tools/make_merge_challenges.py (--draft / --write). Do not edit;
// `--check` refuses a file that is not what the tool writes.
using System.Collections.Generic;

namespace GlimmerGrove.Tests
{
    /// <summary>
    /// The shortest route through every shipped Merge row, found by the tool's 0-1
    /// breadth-first search over quiet slides, as cell and direction in board terms
    /// (<c>D</c> is down the rows). <see cref="ChallengeTests"/> replays each against
    /// <c>MergePuzzle</c> and paces it against the hill (invariant 56n).
    /// </summary>
    static class MergeRoutes
    {
        public static readonly Dictionary<string, string> Shortest = new Dictionary<string, string>
        {
            ["d05_merge"] = "7U 2L 17L 8L 7D 16D 22L 5L 1D 19L",
            ["d69_merge"] = "13R 9D 8R 12R 3D 13R 14U 2R 9U",
            ["d70_merge"] = "17L 11D 16R 3D 4L 14L 13U 2R 3D 18L",
            ["d71_merge"] = "18U 4L 1R 0R 14L 2D 12R 13U 3D 19L",
            ["d72_merge"] = "2D 9L 14U 6R 3D 4L 2D 7L 0D 8L",
            ["d73_merge"] = "15R 16U 5L 4L 13U 19U 7L 8L 6U 1L",
            ["d74_merge"] = "15U 8L 13U 0R 5U 17L 15U 5R 9U 4L 3L",
            ["d75_merge"] = "13R 14D 9D 10R 15U 5R 7D 12R 13D 18R 19U",
            ["d76_merge"] = "0D 9L 3D 8R 14U 10R 12U 9L 15U 2D 7L",
            ["d77_merge"] = "20U 22L 23L 11D 19U 23L 18U 7R 12R 14U 8U",
            ["d78_merge"] = "14L 7D 6R 13R 7D 13R 3D 15L 12R 2R 16U",
            ["d79_merge"] = "9R 8R 16U 10L 7U 13U 7R 5D 17U 11L 7U",
            ["d80_merge"] = "4R 3R 4D 15R 2R 4D 8U 2R 23U 16U 5L",
            ["d81_merge"] = "8D 9L 18U 8R 3D 17R 0D 5R 18U 11U 8L 9L",
            ["d82_merge"] = "20R 2D 16L 14U 3L 21U 15R 23U 17L 20U 4L 14U",
            ["d83_merge"] = "24R 18D 28U 24R 0R 3D 21D 29L 28U 9R 10D 27R 28U",
            ["d84_merge"] = "1D 19L 25U 2L 18R 1D 13R 28U 16L 19L 18U 12R 17U",
            ["d85_merge"] = "7D 25R 1D 27L 26U 29L 25L 24U 9U 3L 12R 1D 14L",
            ["d86_merge"] = "1L 8U 10R 9R 12U 13L 15U 1D 0R 1D 19U 8R 12U",
            ["d87_merge"] = "17D 23L 20U 14L 18U 2R 12R 14D 16R 26R 28U 4R 11U 17U",
            ["d88_merge"] = "0D 24R 25U 22L 15D 20U 19R 14R 15U 21U 9R 5D 11L 9U",
            ["d89_merge"] = "8L 2D 11L 8U 26U 8R 5D 22D 29L 11L 7U 1R 2D 28L",
            ["d90_merge"] = "11U 4L 3D 6L 3D 27L 31U 1D 22R 24R 20D 27L 23U 12L",
            ["d91_merge"] = "24U 12R 17U 11U 5D 29L 25L 24U 12R 26L 24U 12R 28U 17L",
            ["d92_merge"] = "6U 16R 22U 4R 0R 28U 4R 21R 22U 4L 24U 11U 17U 5L",
            ["d93_merge"] = "0R 6U 0R 4D 5L 12U 28L 29L 28U 0R 25L 24U 0R 4D 28L",
            ["d94_merge"] = "10L 8D 14L 2D 1R 2D 11L 8D 14L 25U 19L 26L 25U 13L 18U",
            ["d95_merge"] = "18D 12D 18R 21U 15R 29U 17L 15D 21L 18U 6R 8L 7U 1D 25L",
            ["d96_merge"] = "7D 15D 14R 0D 15D 14R 22R 15D 22R 17D 25L 24U 17R 20D 34L",
            ["d97_merge"] = "18U 10R 11D 25R 6D 27L 32U 25U 28R 21D 30U 28R 30U 9R 11U 4L",
            ["d98_merge"] = "15D 26R 27D 20D 27L 34U 23D 16D 23R 13D 27L 22U 15R 18D 32L 30U 2L",
        };
    }
}
