// Generated by Tools/make_push_challenges.py (--draft / --write). Do not edit;
// `--check` refuses a file that is not what the tool writes.
using System.Collections.Generic;

namespace GlimmerGrove.Tests
{
    /// <summary>
    /// The step-shortest route through every shipped Push row, found by the tool's
    /// breadth-first search over keeper steps, as <c>U D L R</c> in board terms (<c>U</c>
    /// is up the rows). <see cref="ChallengeTests"/> replays each against
    /// <c>SokobanPuzzle</c> and paces it against the hill.
    /// </summary>
    static class PushRoutes
    {
        public static readonly Dictionary<string, string> Shortest = new Dictionary<string, string>
        {
            ["d06_sokoban"] = "ULUURDLLDRDRRULLDLLRUU",
            ["d99_sokoban"] = "DLDDRULLURURRDLLULDRDLL",
            ["d100_sokoban"] = "UDRRULLRUULDDLDLLURRDRUUDRRDLL",
            ["d101_sokoban"] = "ULLRRRULLLDLUUDLDUUURRR",
            ["d102_sokoban"] = "LLULDLLUURDLDRRURDDLDRLLUUU",
            ["d103_sokoban"] = "LLULDLLUURDLDRRURDDLDRLLUUU",
            ["d104_sokoban"] = "LDDRUULULLDRRURDUURDRDLLDULLRDDR",
            ["d105_sokoban"] = "RDLRRDLDLULULLDRRRDRUULULDUL",
            ["d106_sokoban"] = "LRUULDLDLLURRRDRDDLULRURULLL",
            ["d107_sokoban"] = "DLDRDRRULLLULDDRDRURRDLUULL",
            ["d108_sokoban"] = "RULRRULULDLDULUURDLDRRURDDLDLUDL",
            ["d109_sokoban"] = "LRULLDLDURRDLDLULLUURRDUURDDDLL",
            ["d110_sokoban"] = "DULLDRURRDDLRRDLDLULUURULRRDDLDR",
            ["d111_sokoban"] = "DLDDLLURDRULURRLDDRURULURDLLLULD",
            ["d112_sokoban"] = "LLLRDLDDRUULURULLLDRLDRRDRUURULLDURRRRDLLLLULDRDL",
            ["d113_sokoban"] = "LDLRUULDDLDDRRUULLLULLDRRRRUURRDLULDRDLLDDRUDRULUUDLLLDLU",
            ["d114_sokoban"] = "RRRDUURRDDLDLURRUULDLDDDLLURDRUUULULLDRRURDDUURDRDLDLUDL",
            ["d115_sokoban"] = "ULULLDRRURUULDDURRRDLLRRDDLLULULLDRRURUULDDRDLDRRRUULLLDL",
            ["d116_sokoban"] = "DRDLDLDLLURURRLLDDRURUURRDDLUDLLLLRURRURDRDLLLLDLLUURR",
            ["d117_sokoban"] = "LLUULRDDLULLDRUURUURRDLULDULDDDRRUDDDLULUURURDDLRRDLL",
            ["d118_sokoban"] = "LUDLULUURDDRDDLUDLUDDLULURRUURURRDLLULDDURRDLRDDLUUDLUUR",
            ["d119_sokoban"] = "UULRDLLLUUURRDDRRULDDLLDLUULLDRRURDURLLLUURDURRDDRDLLULDLUU",
            ["d120_sokoban"] = "DDLDLLURLUURDDRDRDRRULULLRRDLDLULULUURDDLDRRRULRRDLLLUU",
            ["d121_sokoban"] = "RURRDRULURURRDDLRDDLULLULLDRRRRDRUUULDLRUULDLDRDLLRRRDRUUL",
            ["d122_sokoban"] = "RDURURRDLDLRUULDLLDDRUDDRRUULUURRDLULDLDDRDRUULULDULRRURRDLL",
            ["d123_sokoban"] = "LDURRDLDLDLULLUURDURRDLDDRURULULLLDDRRDRURURULLLDLDRURDRURUL",
            ["d124_sokoban"] = "LDRLDLDDRUUDRURURRDLLLDLLURURURDLLDDRULURURRDDLUDLUURDLLDRDL",
            ["d125_sokoban"] = "RLDDRUDRRULRUULDUUURDRDLDLLLDDRULLURRRLDDRURULRUULDDRDLULLUL",
            ["d126_sokoban"] = "RRDRLULLDRRURDURURDDLDDLLURULULLDRRDDRRRULLRUULLRDRDDLLUUDRR",
            ["d127_sokoban"] = "UDLULULUURDRDLDRDRRUULDULULLLDDRRUDRDRURULLULLDLDRRUUDRD",
        };
    }
}
