using System.Collections.Generic;
using GlimmerGrove.AssetPipeline;
using GlimmerGrove.Daily;
using GlimmerGrove.Utilities;
using NUnit.Framework;

namespace GlimmerGrove.Tests
{
    /// <summary>
    /// That every reward a chest, a streak night or an ad can hand over has a picture, and that
    /// the picture is one the game really loads.
    ///
    /// <para>
    /// <b>It exists because a whole kind was missing and nothing anywhere said so.</b>
    /// <c>ChestDropKind.Utility</c> was added with the action bar (invariant 39b) and
    /// <c>RewardArt</c> was never taught about it, so <c>Icon</c> fell through its
    /// <c>default</c> and answered <b>null</b> — and every caller passes what comes back
    /// straight into a <c>UIKit.Img</c>, so what a player opening a chest actually met was a
    /// <b>white rectangle</b> where the firepot should be (invariant 7b). The compile was
    /// green, the whole suite was green, <c>content.py</c> was green, and
    /// <c>Tools/verify/artnames.py</c> was green — because there is no missing name to find:
    /// the fault is a <em>name that was never written down at all</em>.
    /// </para>
    /// <para>
    /// So this is a property over the enum rather than a list of the kinds somebody remembered
    /// (44e's rule, and this is the second time an enum grew under a table that did not).
    /// Adding a kind now fails here until it is drawn.
    /// </para>
    /// <para>
    /// <b>It checks the address and never the sprite</b>, which is <c>SkinsTests</c>' bargain
    /// for its reason: nothing is loaded in an offline run, so a sprite lookup answers null
    /// whatever the table says, and a check that cannot fail is not a check. Holding the
    /// address to what <c>AssetManifest</c> preloads is what can be proved — and the manifest's
    /// own entries are literals, so they are already held to disk by <c>artnames.py</c>.
    /// </para>
    /// </summary>
    public sealed class RewardArtTests
    {
        /// <summary>
        /// The two kinds with no address, and each is deliberate rather than missing: credits
        /// are the spinning <c>Ui/Coin</c> flipbook, which <c>RewardArt.Glyph</c> attaches, and
        /// the retired run-time dial is generated by <c>Art.Dial</c> rather than loaded.
        /// </summary>
        static bool Drawn(ChestDropKind kind)
            => kind != ChestDropKind.None
            && kind != ChestDropKind.Credits
            && kind != ChestDropKind.RunTime;

        static HashSet<string> Preloaded()
        {
            var loaded = new HashSet<string>();
            foreach (var request in AssetManifest.GlobalAssets()) loaded.Add(request.Address);
            return loaded;
        }

        [Test]
        public void EveryDropKindThatIsDrawnNamesAPictureTheManifestLoads()
        {
            var loaded = Preloaded();
            int checked_ = 0;

            foreach (ChestDropKind kind in System.Enum.GetValues(typeof(ChestDropKind)))
            {
                if (!Drawn(kind)) continue;

                // A kind that names a thing is asked about with one, because that is the only
                // way it is ever drawn. Every utility in the catalog, so a shipped item whose
                // picture was never cut fails here rather than on a player's chest panel.
                if (ChestDropKinds.NeedsItem(kind))
                {
                    foreach (var item in UtilityCatalog.Default.Items)
                    {
                        checked_++;
                        Assert.That(loaded, Contains.Item(AssetManifest.ArtRoot + RewardArt.Address(kind, item.Id)),
                                    $"a chest paying '{item.Id}' draws an address the manifest does "
                                    + "not load - which is a white rectangle, not a missing icon");
                    }

                    continue;
                }

                checked_++;
                var address = RewardArt.Address(kind, null);

                Assert.That(address, Is.Not.Null.And.Not.Empty,
                            $"ChestDropKind.{kind} can be handed to a player and RewardArt has no "
                            + "picture for it - Icon answers null and the caller draws a white rectangle");

                Assert.That(loaded, Contains.Item(AssetManifest.ArtRoot + address),
                            $"ChestDropKind.{kind} names '{address}', which AssetManifest does not load");
            }

            // A walk that finds nothing passes every assertion inside it. The floor is well
            // below the table's size on purpose: it asks "did the walk work", not "is the enum
            // still this big" - see SkinsTests for the afternoon that argument was bought on.
            Assert.Greater(checked_, 5, "the ChestDropKind walk came back nearly empty");
        }

        /// <summary>
        /// That an item id this build has never heard of is drawn as something rather than as
        /// nothing.
        ///
        /// <para>
        /// A chest table is <em>published</em>, so it can name a utility from a newer build —
        /// invariant 20's "content from the future" arriving through the daily chest. The band
        /// reader proves an item id is present and cannot prove the catalog knows it, so the
        /// drawing has to survive one it does not.
        /// </para>
        /// </summary>
        [Test]
        public void AUtilityThisBuildHasNeverHeardOfStillDrawsSomething()
        {
            var address = RewardArt.Address(ChestDropKind.Utility, "a_utility_from_next_year");

            Assert.That(address, Is.Not.Null.And.Not.Empty);
            Assert.That(Preloaded(), Contains.Item(AssetManifest.ArtRoot + address));
        }

        /// <summary>
        /// That a utility drop is named by the <em>thing</em> and not by its kind.
        ///
        /// <para>
        /// <c>NameKeys</c> is indexed by the enum's own value and <c>Utility</c> is one past
        /// its end, so the array answered an empty string for every utility ever dropped — the
        /// same omission as the icon, one line further down, and just as silent: a chest card
        /// with a blank noun under it reads as a layout bug rather than as a missing case.
        /// </para>
        /// </summary>
        [Test]
        public void AUtilityDropIsNamedByTheItemRatherThanByItsKind()
        {
            foreach (var item in UtilityCatalog.Default.Items)
                Assert.That(RewardArt.Name(ChestDropKind.Utility, item.Id),
                            Is.EqualTo(Localization.Loc.Get(item.NameKey)),
                            $"'{item.Id}' is drawn under a name that is not its own");
        }
    }
}
