using System.IO;
using System.Text;
using GlimmerGrove.Content;
using UnityEditor;
using UnityEngine;

namespace GlimmerGrove.EditorTools
{
    /// <summary>
    /// Small authoring conveniences for the fortnightly content drop.
    ///
    /// The pipeline is deliberately plain text files rather than ScriptableObjects:
    /// they diff and merge in review, they can be generated by a script, and they can
    /// be served from a CDN unchanged. These menu items exist so the repetitive parts
    /// — scaffolding a chapter, checking derived par — are not done by hand.
    /// </summary>
    public static class ContentAuthoring
    {
        const string ContentRoot = "Assets/StreamingAssets/Content";

        [MenuItem("Glimmer Grove/Content/Report Levels", false, 40)]
        public static void ReportLevels()
        {
            var load = EditorContentLoader.Load();
            if (load.Index.IsEmpty)
            {
                Debug.LogError("[Glimmer] no content found under " + ContentRoot);
                return;
            }

            var sb = new StringBuilder("[Glimmer] content report\n");
            sb.AppendLine($"{"#",-4}{"level id",-24}{"chapter",-18}{"size",-8}{"par",-6}{"gold",-6}{"silver",-7}stars");

            int order = 0;
            foreach (var level in load.AllLevels())
            {
                var report = LevelValidator.Validate(level);
                string flag = report.HasErrors ? "  BROKEN" : report.IsClean ? "" : "  (warnings)";

                // A hollow reports in sparks rather than turns. Both have a real par and a
                // real ladder, so the columns mean the same thing in both modes - which is the
                // point of deriving a hollow's par rather than authoring a score to beat.
                // Only the classic mode has an authored grid to measure. Everything else
                // says what mode it is, which is the honest answer and does not have to grow a
                // clause when a mode is added.
                string size = level.HasBoard
                    ? level.Layout.Width + "x" + level.Layout.Height
                    : level.Mode.Value;

                string par = level.Tuning.Par.ToString();
                string gold = level.Tuning.GoldThreshold.ToString();
                string silver = level.Tuning.SilverThreshold.ToString();

                sb.AppendLine($"{++order,-4}{level.Id,-24}{level.Chapter,-18}{size,-8}" +
                              $"{par,-6}{gold,-6}{silver,-7}{report.ComputedPar}{flag}");
            }

            Debug.Log(sb.ToString());
        }

        [MenuItem("Glimmer Grove/Content/Create Chapter Template", false, 41)]
        public static void CreateChapterTemplate()
        {
            string path = EditorUtility.SaveFilePanel(
                "New chapter", Path.Combine(ContentRoot, "chapters"), "c02_new_chapter", "json");
            if (string.IsNullOrEmpty(path)) return;

            string id = Path.GetFileNameWithoutExtension(path);
            if (!ChapterId.TryParse(id, out _, out string error))
            {
                EditorUtility.DisplayDialog("Invalid chapter id", $"'{id}' is not usable: {error}", "OK");
                return;
            }

            File.WriteAllText(path, Template(id));
            AssetDatabase.Refresh();

            Debug.Log($"[Glimmer] created {path}\n" +
                      "Next: run Content \u25B8 Sync Manifest. It adopts the chapter into " +
                      "manifest.json, picks an order and fills in its level list \u2014 nothing here " +
                      "needs editing by hand. Then add its strings to the localisation tables; " +
                      "validation names every key it wants.\n" +
                      $"Token grammar: {LevelLayout.Grammar}");
            EditorUtility.RevealInFinder(path);
        }

        /// <summary>
        /// A chapter skeleton.
        ///
        /// Par is left out on purpose — it is derived from the board, so an omitted par
        /// can never be wrong while a typed one can. So is <c>order</c>: it lives in the
        /// manifest, and a template that emitted one would have every new chapter
        /// claiming the same position. The backdrop is written out rather than left to a
        /// default, because a chapter that does not name its own art ends up sharing
        /// another chapter's asset bundle.
        /// </summary>
        static string Template(string chapterId) =>
$@"{{
  ""schemaVersion"": {ContentSchema.Version},
  ""id"": ""{chapterId}"",

  ""accent"": ""#FFC93C"",
  ""slate"": ""#123640"",
  ""backdrop"": ""sky_00"",
  ""mapStrips"": [""map1_strip0"", ""map1_strip1"", ""map1_strip2"", ""map1_strip3"", ""map1_strip4"", ""map1_strip5""],

  ""levels"": [
    {{
      ""id"": ""{chapterId}_01"",
      ""width"": 5,
      ""height"": 5,
      ""mapX"": 0.33,
      ""mapY"": 0.2,
      ""rows"": [
        "". . . . ."",
        "". . . . ."",
        "". . . . ."",
        "". . . . ."",
        "". . . . .""
      ]
    }}
  ]
}}
";
    }
}
