using System.IO;
using System.Text;
using GlimmerGrove.Content;
using UnityEditor;
using UnityEngine;

namespace GlimmerGrove.EditorTools
{
    /// <summary>
    /// Small authoring conveniences for the fortnightly content drop.
    ///
    /// The pipeline is deliberately plain text files rather than ScriptableObjects:
    /// they diff and merge in review, they can be generated by a script, and they can
    /// be served from a CDN unchanged. These menu items exist so the repetitive parts
    /// — scaffolding a chapter, checking derived par — are not done by hand.
    /// </summary>
    public static class ContentAuthoring
    {
        const string ContentRoot = "Assets/StreamingAssets/Content";

        [MenuItem("Glimmer Grove/Content/Report Levels", false, 40)]
        public static void ReportLevels()
        {
            var load = EditorContentLoader.Load();
            if (load.Catalog.IsEmpty)
            {
                Debug.LogError("[Glimmer] no content found under " + ContentRoot);
                return;
            }

            var sb = new StringBuilder("[Glimmer] content report\n");
            sb.AppendLine($"{"#",-4}{"level id",-24}{"chapter",-18}{"size",-8}{"par",-6}{"gold",-6}{"silver",-7}stars");

            int order = 0;
            foreach (var level in load.Catalog.Levels)
            {
                var report = LevelValidator.Validate(level);
                string flag = report.HasErrors ? "  BROKEN" : report.IsClean ? "" : "  (warnings)";

                sb.AppendLine($"{++order,-4}{level.Id,-24}{level.Chapter,-18}" +
                              $"{level.Layout.Width + "x" + level.Layout.Height,-8}" +
                              $"{level.Tuning.Par,-6}{level.Tuning.GoldThreshold,-6}" +
                              $"{level.Tuning.SilverThreshold,-7}{report.ComputedPar}{flag}");
            }

            Debug.Log(sb.ToString());
        }

        [MenuItem("Glimmer Grove/Content/Create Chapter Template", false, 41)]
        public static void CreateChapterTemplate()
        {
            string path = EditorUtility.SaveFilePanel(
                "New chapter", Path.Combine(ContentRoot, "chapters"), "c02_new_chapter", "json");
            if (string.IsNullOrEmpty(path)) return;

            string id = Path.GetFileNameWithoutExtension(path);
            if (!ChapterId.TryParse(id, out _, out string error))
            {
                EditorUtility.DisplayDialog("Invalid chapter id", $"'{id}' is not usable: {error}", "OK");
                return;
            }

            File.WriteAllText(path, Template(id));
            AssetDatabase.Refresh();

            Debug.Log($"[Glimmer] created {path}\n" +
                      $"Add an entry to {ContentRoot}/manifest.json to publish it, and add its " +
                      $"strings to the localisation tables.\nToken grammar: {LevelLayout.Grammar}");
            EditorUtility.RevealInFinder(path);
        }

        /// <summary>
        /// A chapter skeleton. Par is left out on purpose — it is derived from the
        /// board, so an omitted par can never be wrong, while a typed one can.
        /// </summary>
        static string Template(string chapterId) =>
$@"{{
  ""schemaVersion"": {ContentSchema.Version},
  ""id"": ""{chapterId}"",
  ""order"": 20,

  ""accent"": ""#FFC93C"",
  ""slate"": ""#123640"",
  ""backdrop"": ""play_0"",
  ""mapStrips"": [""strip0"", ""strip1"", ""strip2""],

  ""levels"": [
    {{
      ""id"": ""{chapterId}_01"",
      ""width"": 5,
      ""height"": 5,
      ""mapX"": 0.33,
      ""mapY"": 0.2,
      ""rows"": [
        "". . . . ."",
        "". . . . ."",
        "". . . . ."",
        "". . . . ."",
        "". . . . .""
      ]
    }}
  ]
}}
";
    }
}
