#if UNITY_IOS
using System.Collections.Generic;
using System.IO;
using System.Text;
using GlimmerGrove.Content;
using GlimmerGrove.Localization;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;
using UnityEngine;

namespace GlimmerGrove.EditorTools
{
    /// <summary>
    /// Writes the tracking usage description into the generated Xcode project.
    ///
    /// <para>
    /// <b>Why this is a build step rather than a Player Settings field.</b> Unity has no field
    /// for <c>NSUserTrackingUsageDescription</c>, so the only alternatives are editing
    /// <c>Info.plist</c> by hand after every build - which is a step somebody forgets on
    /// shipping week, exactly as this project has already learned twice - or a post-processor.
    /// It is also not optional: iOS refuses to present the tracking prompt at all when the key
    /// is missing, and the failure is silent. The dialog never appears, every player is
    /// non-consented, and the build passes review with iOS ad revenue quietly near zero.
    /// </para>
    /// <para>
    /// <b>The sentence matters more than it looks.</b> Apple reviews it, and a description that
    /// merely restates the dialog ("this app would like to track you") is a documented
    /// rejection. It has to say what the data is used for: relevant ads, which keep the game
    /// free. It is the loc key <see cref="TrackingKey"/>, so it is translated, checked and
    /// reviewed exactly like every other player-facing string, and never typed into code.
    /// </para>
    /// <para>
    /// <b>One translation per shipped language</b>, because Apple expects the purpose string in
    /// the language the dialog is drawn in, and an English sentence inside a German dialog is a
    /// half-translated permission request. <see cref="WriteTranslations"/> writes an
    /// <c>InfoPlist.strings</c> into an <c>{code}.lproj</c> folder for every entry of
    /// <see cref="Loc.Languages"/>, links each into the app target, and declares the same list
    /// in <c>CFBundleLocalizations</c>. That also tells iOS and the App Store which languages the
    /// app speaks: the listing derives its language line from these folders, and iOS offers a
    /// per-app language choice in Settings once more than one is declared. The base
    /// <c>Info.plist</c> keeps the English sentence for any device language not listed.
    /// </para>
    /// <para>
    /// <b>A missing translation fails the build</b> rather than shipping an English line in a
    /// translated dialog, and a missing English line fails it rather than shipping no key at
    /// all - which would be the silent no-prompt failure above. <c>TranslationTests</c> catches
    /// both long before a Mac build does.
    /// </para>
    /// <para>
    /// Everything else iOS needs for ads is already handled elsewhere and is not duplicated
    /// here: the <c>SKAdNetworkItems</c> list belongs to the mediation SDK, which maintains it
    /// per network and adds it in its own post-processor, and the engine's privacy manifest is
    /// generated by Unity. Restating either would create a second copy to go stale.
    /// </para>
    /// <para>
    /// <b>The Google Mobile Ads plugin writes this same key</b>, from a field in
    /// <c>GoogleMobileAdsSettings</c>, in its own <c>PListProcessor</c>. Two writers for one
    /// value is exactly the second-source-of-truth problem this codebase keeps refusing, so the
    /// resolution is deliberate rather than incidental: <b>leave the plugin's "User Tracking
    /// Usage Description" field empty</b> and this is the only writer. The order makes that
    /// safe either way - the plugin uses the default callback order of 1 and this one declares
    /// 100, so this runs last and wins - but a filled-in field there would be a setting
    /// somebody changed and watched do nothing, which is worse than a conflict that errors.
    /// </para>
    /// <para>
    /// This one is preferred for the reason the loc keys are gated: the sentence Apple reads is
    /// copy, it belongs in version control where a diff shows it changing, and it must not
    /// depend on a value typed once into a <c>.asset</c> that nobody reviews. It also keeps
    /// working if the CMP is ever swapped for another one.
    /// </para>
    /// </summary>
    public static class IosPrivacyPlist
    {
        /// <summary>
        /// The loc key of what the player reads above Apple's Allow / Ask App Not to Track
        /// buttons. Deliberately a plain sentence with no jargon and no plea: reviewers reject
        /// copy that is vague, and players refuse copy that begs.
        /// </summary>
        internal const string TrackingKey = "ui.privacy.tracking_usage";

        const string TrackingPlistKey = "NSUserTrackingUsageDescription";

        /// <summary>Where the per-language folders are written, inside the generated Xcode project.</summary>
        const string LocalizationFolder = "GemfireLocalizations";

        [PostProcessBuild(100)]
        public static void OnPostProcessBuild(BuildTarget target, string pathToBuiltProject)
        {
            if (target != BuildTarget.iOS) return;

            string plistPath = Path.Combine(pathToBuiltProject, "Info.plist");
            if (!File.Exists(plistPath))
            {
                Debug.LogError($"[Privacy] no Info.plist at '{plistPath}'; the tracking prompt " +
                               "will never appear and iOS ads will not be personalised");
                return;
            }

            // Read every sentence before touching anything, so a missing one stops the build
            // with the project exactly as Unity left it.
            var sentences = TrackingSentences();

            var plist = new PlistDocument();
            plist.ReadFromFile(plistPath);

            // Set unconditionally rather than only when absent. A stale description left by an
            // earlier build is worse than none: it passes every check here and is the thing
            // Apple actually reads. English is the base for any device language not shipped.
            plist.root.SetString(TrackingPlistKey, sentences[Loc.FallbackLanguage]);

            // The languages this app speaks, declared once and replaced whole on every build so
            // an append build cannot leave a stale list behind.
            var localizations = plist.root.CreateArray("CFBundleLocalizations");
            foreach (var language in Loc.Languages) localizations.AddString(LprojName(language.Code));

            // Export compliance, declared here rather than answered by hand on every upload.
            //
            // App Store Connect asks the encryption question for each build, and answering it
            // in the console is a step somebody performs while trying to ship - which is
            // exactly when a wrong answer is cheapest to give and most expensive to have
            // given. Declaring it in the binary means the question stops being asked and the
            // answer lives in version control where a diff shows it changing.
            //
            // False is the correct answer for this game, and the reason is narrow enough to
            // write down: the exemption covers an app whose only cryptography is the HTTPS
            // its platform provides, plus standard hashing that is not used to protect data
            // in transit. Everything here fits - Firebase and the ad SDKs talk TLS through
            // the OS, SaveChecksum and the daily-chest roll are FNV-1a and xorshift over
            // local data, and SHA-256 appears once, on the Sign in with Apple nonce, which
            // is a replay guard rather than a cipher. Nothing in this app implements or
            // bundles an encryption algorithm of its own.
            //
            // If that ever stops being true - a bundled cipher, an encrypted save, a custom
            // secure channel - this line has to change with it, because it is a declaration
            // to a regulator rather than a convenience.
            plist.root.SetBoolean("ITSAppUsesNonExemptEncryption", false);

            // Firebase Analytics starts with collection OFF, so nothing is measured before the
            // consent gateway has answered.
            //
            // The iOS twin of the meta-data in GlimmerMeasurement.androidlib, and it exists for
            // the same reason: Firebase enables collection the instant its native SDK
            // initialises, which is earlier than any managed code here can run. AnalyticsSetup
            // disabling it at start-up would be closing the window after the fact, which for a
            // regulator is not closing it. This is the only thing that starts the SDK disabled.
            //
            // What it costs: collection then depends entirely on AnalyticsSetup.Push() running,
            // so a break there measures nothing rather than measuring too much. That is the
            // right way round for a consent gate and the wrong way round for a retention test,
            // which is why the enable path is checked on a device - "[Analytics] collection
            // enabled" in the log on any launch where consent is granted.
            plist.root.SetBoolean("FIREBASE_ANALYTICS_COLLECTION_ENABLED", false);

            plist.WriteToFile(plistPath);

            Debug.Log("[Privacy] NSUserTrackingUsageDescription, CFBundleLocalizations, " +
                      "ITSAppUsesNonExemptEncryption and FIREBASE_ANALYTICS_COLLECTION_ENABLED " +
                      "written into Info.plist");

            WriteTranslations(pathToBuiltProject, sentences);
            LinkTrackingFramework(pathToBuiltProject);
        }

        /// <summary>
        /// The tracking sentence in every shipped language, read from the same tables the game
        /// reads. Throws - failing the build - when a table is missing, unreadable, or lacks the
        /// sentence: a build that cannot say why it asks must not be built.
        /// </summary>
        static Dictionary<string, string> TrackingSentences()
        {
            var sentences = new Dictionary<string, string>();

            foreach (var language in Loc.Languages)
            {
                string path = Path.Combine(Application.streamingAssetsPath,
                                           ContentPaths.Localisation(language.Code));
                if (!File.Exists(path))
                    throw new BuildFailedException($"[Privacy] no string table at '{path}' for '{language.Code}'");

                var table = LocTable.Parse(File.ReadAllText(path), out string error);
                if (error != null)
                    throw new BuildFailedException($"[Privacy] {language.Code}.json could not be read: {error}");

                if (!table.TryGet(TrackingKey, out string sentence) || string.IsNullOrWhiteSpace(sentence))
                    throw new BuildFailedException($"[Privacy] {language.Code}.json has no '{TrackingKey}'; " +
                                                   "the tracking prompt would be drawn without its reason");

                sentences[language.Code] = sentence.Trim();
            }

            return sentences;
        }

        /// <summary>
        /// One <c>{code}.lproj/InfoPlist.strings</c> per shipped language, each linked into the
        /// app target as a folder reference so Xcode copies the folder into the bundle as it is.
        ///
        /// <para>
        /// The folders are written fresh on every build and linked only when not already linked,
        /// so an append build neither duplicates a reference (which Xcode rejects as two
        /// commands producing one file) nor keeps a sentence from the previous build.
        /// </para>
        /// </summary>
        static void WriteTranslations(string pathToBuiltProject, Dictionary<string, string> sentences)
        {
            string projectPath = PBXProject.GetPBXProjectPath(pathToBuiltProject);
            if (!File.Exists(projectPath))
                throw new BuildFailedException($"[Privacy] no Xcode project at '{projectPath}'; " +
                                               "the tracking prompt's translations cannot be linked");

            RefuseAnotherInfoPlistStrings(pathToBuiltProject);

            var project = new PBXProject();
            project.ReadFromFile(projectPath);
            string app = project.GetUnityMainTargetGuid();

            foreach (var language in Loc.Languages)
            {
                string lproj = LprojName(language.Code) + ".lproj";
                string relative = LocalizationFolder + "/" + lproj;
                string folder = Path.Combine(pathToBuiltProject, LocalizationFolder, lproj);

                Directory.CreateDirectory(folder);
                File.WriteAllText(Path.Combine(folder, "InfoPlist.strings"),
                                  StringsLine(TrackingPlistKey, sentences[language.Code]),
                                  new UTF8Encoding(false));

                // Relative to the project root (SOURCE_ROOT), never absolute: an absolute path
                // is the build Mac's own directory and breaks the moment the Xcode project is
                // moved, archived elsewhere or opened on another machine.
                if (project.FindFileGuidByProjectPath(relative) == null)
                {
                    string guid = project.AddFolderReference(relative, relative, PBXSourceTree.Source);
                    project.AddFileToBuild(app, guid);
                }

                project.AddKnownRegion(LprojName(language.Code));
            }

            project.WriteToFile(projectPath);

            Debug.Log($"[Privacy] tracking sentence localised into {sentences.Count} languages: " +
                      string.Join(", ", sentences.Keys));
        }

        /// <summary>Unity's iOS test target; its files never reach the app bundle.</summary>
        const string TestsTargetFolder = "Unity-iPhone Tests";

        /// <summary>
        /// Fails the build if anything else in the generated project carries an
        /// <c>InfoPlist.strings</c> that would land at the bundle root beside these.
        ///
        /// <para>
        /// A plugin or a future template that adds one to the app would make Xcode refuse the
        /// build with "multiple commands produce" - or, worse, keep one of the two and silently
        /// drop the other's keys. Files inside a <c>.bundle</c>, a framework or the CocoaPods
        /// tree belong to those packages and are copied inside them, so they cannot collide and
        /// are not counted. Nor is the template's own <c>Unity-iPhone Tests/en.lproj</c> copy:
        /// it belongs to the separate test target and never reaches the app bundle (it failed
        /// the 1.0.7 store build, 2026-10-08).
        /// </para>
        /// </summary>
        static void RefuseAnotherInfoPlistStrings(string pathToBuiltProject)
        {
            string ours = Path.GetFullPath(Path.Combine(pathToBuiltProject, LocalizationFolder));

            foreach (string file in Directory.GetFiles(pathToBuiltProject, "InfoPlist.strings",
                                                       SearchOption.AllDirectories))
            {
                string full = Path.GetFullPath(file).Replace('\\', '/');
                if (full.StartsWith(ours.Replace('\\', '/') + "/")) continue;
                if (full.Contains(".bundle/") || full.Contains(".framework/") ||
                    full.Contains(".xcframework/") || full.Contains("/Pods/")) continue;
                if (full.Contains("/" + TestsTargetFolder + "/")) continue;

                throw new BuildFailedException(
                    $"[Privacy] '{file}' is another InfoPlist.strings in the app; it would collide " +
                    $"with the tracking prompt's translations in {LocalizationFolder}. Merge its keys " +
                    "into the string tables or remove it.");
            }
        }

        /// <summary>
        /// The folder name iOS matches a device language against. The game's codes are already
        /// Apple's for every shipped language: <c>pt</c> rather than <c>pt-BR</c> on purpose, so
        /// a European Portuguese device falls back to the Brazilian table rather than to English.
        /// </summary>
        internal static string LprojName(string code) => code;

        /// <summary>
        /// One <c>"key" = "value";</c> line in the <c>.strings</c> format, escaped the way that
        /// format requires: a backslash, a quote and a line break are the three characters that
        /// would end or corrupt the value.
        /// </summary>
        internal static string StringsLine(string key, string value)
        {
            string escaped = value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n");
            return $"\"{key}\" = \"{escaped}\";\n";
        }

        /// <summary>
        /// Links <c>AppTrackingTransparency.framework</c>, which nothing else does.
        ///
        /// <para>
        /// Unity copies a native plugin into the generated project but does not link the system
        /// frameworks it calls into, and <c>ATTrackingManager</c> lives in one that is not linked
        /// by default. Without this the build fails at the very end, in the linker, with
        /// undefined symbols for <c>_OBJC_CLASS_$_ATTrackingManager</c> - after twenty minutes of
        /// compiling, and with an error that names Apple's class rather than our file.
        /// </para>
        /// <para>
        /// <b>Weakly linked</b>, deliberately. The framework arrived in iOS 14 and the plugin
        /// guards every call behind an availability check, so a weak link lets the app launch on
        /// anything older with the symbol simply absent. A strong link would refuse to load the
        /// binary at all on those devices - a crash on start rather than a feature that is
        /// quietly unavailable.
        /// </para>
        /// <para>
        /// Added to the <c>UnityFramework</c> target rather than the app target, because that is
        /// where Unity puts native plugins in a modern generated project - the app target is a
        /// thin shell that loads it.
        /// </para>
        /// </summary>
        static void LinkTrackingFramework(string pathToBuiltProject)
        {
            string projectPath = PBXProject.GetPBXProjectPath(pathToBuiltProject);

            if (!File.Exists(projectPath))
            {
                Debug.LogError($"[Privacy] no Xcode project at '{projectPath}'; " +
                               "AppTrackingTransparency will not be linked and the build will " +
                               "fail in the linker");
                return;
            }

            var project = new PBXProject();
            project.ReadFromFile(projectPath);

            project.AddFrameworkToProject(project.GetUnityFrameworkTargetGuid(),
                                          "AppTrackingTransparency.framework", weak: true);

            project.WriteToFile(projectPath);

            Debug.Log("[Privacy] AppTrackingTransparency.framework linked (weak) into UnityFramework");
        }
    }
}
#endif
