#if UNITY_IOS
using System.IO;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;
using UnityEngine;

namespace GlimmerGrove.EditorTools
{
    /// <summary>
    /// Writes the tracking usage description into the generated Xcode project.
    ///
    /// <para>
    /// <b>Why this is a build step rather than a Player Settings field.</b> Unity has no field
    /// for <c>NSUserTrackingUsageDescription</c>, so the only alternatives are editing
    /// <c>Info.plist</c> by hand after every build — which is a step somebody forgets on
    /// shipping week, exactly as this project has already learned twice — or a post-processor.
    /// It is also not optional: iOS refuses to present the tracking prompt at all when the key
    /// is missing, and the failure is silent. The dialog never appears, every player is
    /// non-consented, and the build passes review with iOS ad revenue quietly near zero.
    /// </para>
    /// <para>
    /// <b>The sentence matters more than it looks.</b> Apple reviews it, and a description that
    /// merely restates the dialog ("this app would like to track you") is a documented
    /// rejection. It has to say what the player gets. This one says the two true things: it
    /// keeps the game free, and it is the difference between a relevant ad and a random one.
    /// It must be translated for every language the store listing supports — that is an
    /// <c>InfoPlist.strings</c> file per locale in the Xcode project, and it is deliberately
    /// <em>not</em> generated here, because the loc keys in this game are gated by a build
    /// check and a string invented at build time would slip past it.
    /// </para>
    /// <para>
    /// Everything else iOS needs for ads is already handled elsewhere and is not duplicated
    /// here: the <c>SKAdNetworkItems</c> list belongs to the mediation SDK, which maintains it
    /// per network and adds it in its own post-processor, and the engine's privacy manifest is
    /// generated by Unity. Restating either would create a second copy to go stale.
    /// </para>
    /// <para>
    /// <b>The Google Mobile Ads plugin writes this same key</b>, from a field in
    /// <c>GoogleMobileAdsSettings</c>, in its own <c>PListProcessor</c>. Two writers for one
    /// value is exactly the second-source-of-truth problem this codebase keeps refusing, so the
    /// resolution is deliberate rather than incidental: <b>leave the plugin's "User Tracking
    /// Usage Description" field empty</b> and this is the only writer. The order makes that
    /// safe either way — the plugin uses the default callback order of 1 and this one declares
    /// 100, so this runs last and wins — but a filled-in field there would be a setting
    /// somebody changed and watched do nothing, which is worse than a conflict that errors.
    /// </para>
    /// <para>
    /// This one is preferred for the reason the loc keys are gated: the sentence Apple reads is
    /// copy, it belongs in version control where a diff shows it changing, and it must not
    /// depend on a value typed once into a <c>.asset</c> that nobody reviews. It also keeps
    /// working if the CMP is ever swapped for another one.
    /// </para>
    /// </summary>
    public static class IosPrivacyPlist
    {
        /// <summary>
        /// What the player reads above Apple's Allow / Ask App Not to Track buttons.
        ///
        /// Deliberately a plain sentence with no jargon and no plea. Reviewers reject copy
        /// that is vague, and players refuse copy that begs.
        /// </summary>
        const string TrackingUsage =
            "Glimmer Groove is free to play. Allowing this lets us show ads that are relevant " +
            "to you rather than random ones, which is what pays for the glades.";

        [PostProcessBuild(100)]
        public static void OnPostProcessBuild(BuildTarget target, string pathToBuiltProject)
        {
            if (target != BuildTarget.iOS) return;

            string plistPath = Path.Combine(pathToBuiltProject, "Info.plist");
            if (!File.Exists(plistPath))
            {
                Debug.LogError($"[Privacy] no Info.plist at '{plistPath}'; the tracking prompt " +
                               "will never appear and iOS ads will not be personalised");
                return;
            }

            var plist = new PlistDocument();
            plist.ReadFromFile(plistPath);

            // Set unconditionally rather than only when absent. A stale description left by an
            // earlier build is worse than none: it passes every check here and is the thing
            // Apple actually reads.
            plist.root.SetString("NSUserTrackingUsageDescription", TrackingUsage);

            // Export compliance, declared here rather than answered by hand on every upload.
            //
            // App Store Connect asks the encryption question for each build, and answering it
            // in the console is a step somebody performs while trying to ship — which is
            // exactly when a wrong answer is cheapest to give and most expensive to have
            // given. Declaring it in the binary means the question stops being asked and the
            // answer lives in version control where a diff shows it changing.
            //
            // False is the correct answer for this game, and the reason is narrow enough to
            // write down: the exemption covers an app whose only cryptography is the HTTPS
            // its platform provides, plus standard hashing that is not used to protect data
            // in transit. Everything here fits — Firebase and the ad SDKs talk TLS through
            // the OS, SaveChecksum and the daily-chest roll are FNV-1a and xorshift over
            // local data, and SHA-256 appears once, on the Sign in with Apple nonce, which
            // is a replay guard rather than a cipher. Nothing in this app implements or
            // bundles an encryption algorithm of its own.
            //
            // If that ever stops being true — a bundled cipher, an encrypted save, a custom
            // secure channel — this line has to change with it, because it is a declaration
            // to a regulator rather than a convenience.
            plist.root.SetBoolean("ITSAppUsesNonExemptEncryption", false);

            plist.WriteToFile(plistPath);

            Debug.Log("[Privacy] NSUserTrackingUsageDescription and ITSAppUsesNonExemptEncryption " +
                      "written into Info.plist");

            LinkTrackingFramework(pathToBuiltProject);
        }

        /// <summary>
        /// Links <c>AppTrackingTransparency.framework</c>, which nothing else does.
        ///
        /// <para>
        /// Unity copies a native plugin into the generated project but does not link the system
        /// frameworks it calls into, and <c>ATTrackingManager</c> lives in one that is not linked
        /// by default. Without this the build fails at the very end, in the linker, with
        /// undefined symbols for <c>_OBJC_CLASS_$_ATTrackingManager</c> — after twenty minutes of
        /// compiling, and with an error that names Apple's class rather than our file.
        /// </para>
        /// <para>
        /// <b>Weakly linked</b>, deliberately. The framework arrived in iOS 14 and the plugin
        /// guards every call behind an availability check, so a weak link lets the app launch on
        /// anything older with the symbol simply absent. A strong link would refuse to load the
        /// binary at all on those devices — a crash on start rather than a feature that is
        /// quietly unavailable.
        /// </para>
        /// <para>
        /// Added to the <c>UnityFramework</c> target rather than the app target, because that is
        /// where Unity puts native plugins in a modern generated project — the app target is a
        /// thin shell that loads it.
        /// </para>
        /// </summary>
        static void LinkTrackingFramework(string pathToBuiltProject)
        {
            string projectPath = PBXProject.GetPBXProjectPath(pathToBuiltProject);

            if (!File.Exists(projectPath))
            {
                Debug.LogError($"[Privacy] no Xcode project at '{projectPath}'; " +
                               "AppTrackingTransparency will not be linked and the build will " +
                               "fail in the linker");
                return;
            }

            var project = new PBXProject();
            project.ReadFromFile(projectPath);

            project.AddFrameworkToProject(project.GetUnityFrameworkTargetGuid(),
                                          "AppTrackingTransparency.framework", weak: true);

            project.WriteToFile(projectPath);

            Debug.Log("[Privacy] AppTrackingTransparency.framework linked (weak) into UnityFramework");
        }
    }
}
#endif
